export enum K8SHealthStatus {
    ALL_OK = 'ALL_OK',
    DOWN = 'DOWN',
    NOT_AVAILABLE = 'NOT_AVAILABLE',
    NOT_READY = 'NOT_READY',
    DEPENDENCIES_TIMEOUT = 'DEPENDENCIES_TIMEOUT',
    DEPENDENCIES_NOT_REACHABLE = 'DEPENDENCIES_NOT_REACHABLE'
}